server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update # Disable schema generation by JPA
    defer-datasource-initialization: true

ogs:
  sample-threshold:
    minWaterContentPercent: 5.0
    maxWaterContentPercent: 150.0
    minUnitWeightKNPerM3: 12.0
    maxUnitWeightKNPerM3: 26.0
    minShearStrengthKPa: 2.0
    maxShearStrengthKPa: 1000.0

security:
  user:
    username: user
    password: password #store in keyvault
    role: USER
